[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pylib-parameters"
version = "0.1.0"
description = "..."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "DHL" }
]

dependencies = [
    "pylib-gdal",
    "pylib-qgis",
    "pylib-qttools",
    "pint",
]

[project.optional-dependencies]
numpy = [
    "numpy",
]
osgeo = [
    "ogr",
    "gdal",
    "osr",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]